# Generated by Django 3.0.2 on 2020-01-11 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='audio_file',
            new_name='music_file',
        ),
        migrations.RemoveField(
            model_name='album',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
        migrations.AddField(
            model_name='music',
            name='music_coverArt',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
