# Generated by Django 3.0.2 on 2020-01-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200111_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_coverArt',
            field=models.CharField(default='https://bit.ly/2FDO3LI', max_length=2083),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(blank=True, upload_to='musics/'),
        ),
    ]
