# Generated by Django 3.0.2 on 2020-01-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200119_2145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Generes',
            new_name='Genres',
        ),
    ]
