# Generated by Django 3.0.2 on 2020-01-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20200119_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='genre_logo',
            field=models.CharField(default='https://i.ytimg.com/vi/5Peo-ivmupE/maxresdefault.jpg', max_length=2083),
        ),
        migrations.AlterField(
            model_name='albums',
            name='album_logo',
            field=models.CharField(default='https://i.ytimg.com/vi/5Peo-ivmupE/maxresdefault.jpg', max_length=2083),
        ),
    ]
