# Generated by Django 3.0.2 on 2020-02-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20200203_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=250)),
                ('image', models.CharField(default='https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fclipart-library.com%2Fimg%2F870190.png&f=1&nofb=1', max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Distributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=250)),
                ('logo', models.CharField(default='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmdbootstrap.com%2Fimg%2FPhotos%2FOthers%2Fplaceholder-avatar.jpg&f=1&nofb=1', max_length=2083)),
            ],
        ),
        migrations.RemoveField(
            model_name='albums',
            name='artist',
        ),
        migrations.AddField(
            model_name='albums',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Distributors'),
        ),
        migrations.AddField(
            model_name='musics',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artists'),
        ),
    ]
