# Generated by Django 3.0.2 on 2020-02-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20200205_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
