# Generated by Django 3.0.2 on 2020-02-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_albums_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musics',
            name='music_artist',
        ),
    ]
