# Generated by Django 3.0.2 on 2020-02-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20200209_2324'),
        ('music', '0017_auto_20200210_1024'),
    ]

    operations = [
    ]
