# Generated by Django 3.0.2 on 2020-02-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_merge_20200210_1553'),
        ('music', '0018_merge_20200210_1207'),
    ]

    operations = [
    ]
