# Generated by Django 3.0.2 on 2020-01-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicLib', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_coverArt',
            field=models.CharField(default='https://bit.ly/2FDO3LI', max_length=2083),
        ),
    ]
