# Generated by Django 3.0.2 on 2020-01-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicLib', '0003_music_music_coverart'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, upload_to='musics/'),
        ),
    ]
