# Generated by Django 3.0.2 on 2020-01-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200122_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
