# Generated by Django 3.0.2 on 2020-01-27 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_customers_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='country',
            field=models.CharField(choices=[('NEP', 'Nepal'), ('IND', 'India'), ('USA', 'USA')], default='Nepal', max_length=3),
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customers',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1),
        ),
    ]
