# Generated by Django 3.0.2 on 2020-02-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200127_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='m_name',
        ),
    ]
