# Generated by Django 3.0.2 on 2020-02-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200210_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='dob',
        ),
    ]
